### PR TITLE
Version 1.0.4 

### PR DESCRIPTION
**Pull request by pedroernesto**
A population study to compare average morphometrics to experimenta data has been included.
Besides, tests code has been reorganized.

### CODE REVIEW

**Comment by appukuttan-shailesh** [comment]
Merge conflicts need to be resolved.

**Comment by pedroernesto** [comment]
Conflicts solved with:

```
> git clone https://github.com/appukuttan-shailesh/morphounit.git morphounit_sh
> cd morphounit_sh/
> git checkout -b pedroernesto-master master
> git pull https://github.com/pedroernesto/morphounit.git master
> grep -lr '<<<<<<<' . | xargs git checkout --theirs
> git add setup.py morphounit/utils.py morphounit/tests/morph_circuits/test_CellDensityTest.py morphounit/tests/morph_cells/test_NeuroM_SomaDiamTest_Range.py morphounit/tests/morph_cells/test_NeuroM_MorphStats.py morphounit/tests/__init__.py morphounit/plots/plot_txt_table.py morphounit/plots/plot_score_bars_morp_stats.py morphounit/plots/__init__.py
> git rm morphounit/tests/test_NeuroM_MorphStats_pop.py morphounit/tests/test_NeuroM_SomaDiamTest_MeanSD.py
> git checkout master
> git commit -m 'Adding a population study to test average morphometrics'
> git push origin master
```

**Comment by appukuttan-shailesh** [comment]
@pedroernesto: you closed the pull request without merging it. Was that intentional?

**Comment by pedroernesto** [comment]
The code is merged and tested. I am not sure what you mean.

**Comment by pedroernesto** [comment]
@appukuttan-shailesh you were right, there was still conflicts in file:
morphounit/tests/morph_circuits/test_LayerHeightTest.py

I just corrected it.

**Pull request merged**
